server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Archivos estáticos del frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Imágenes - servir directamente desde la carpeta montada
    location /uploads/ {
        alias /usr/share/nginx/html/uploads/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
