FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies (only production)
COPY package*.json ./
RUN npm install --production

# Copy application files
COPY . .

# Expose port
EXPOSE 3000

# Start command
CMD ["npm", "start"]
